version: "3.8"

services:
  mongodb:
    image: "mongo:latest"
    container_name: "patch_hub_mongodb"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "hGt7uB3pZrDf9iJk1qWe4rTy6uIoP2aS"
    ports:
      - "27017:27017"
    networks:
      - "patch_hub_network"
    volumes:
      - "patch_hub_db_volume:/data/db"

  nats-server:
    image: "nats:latest"
    container_name: "patch_hub_nats"
    command: "-c /etc/nats/nats-server.conf"
    restart: "always"
    ports:
      - "4222:4222"
      - "4443:4443"
    volumes:
      - "./nats-server.conf:/etc/nats/nats-server.conf"

  patch-hub-server:
    depends_on:
      - "mongodb"
    image: "ghcr.io/blogic-datht/patch-hub-server:latest"
    container_name: "patch_hub_server"
    restart: "always"
    environment:
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "hGt7uB3pZrDf9iJk1qWe4rTy6uIoP2aS"
      MONGO_HOST: "mongodb"
      MONGO_PORT: "27017"
      MONGO_DB: "patches"
    ports:
      - "4333:3000"
    volumes:
      - "patch_hub_resource_volume:/app/public"
    networks:
      - "patch_hub_network"

  patch-hub-dashboard:
    image: "ghcr.io/blogic-datht/patch-hub-dashboard:latest"
    container_name: "patch_hub_dashboard"
    ports:
      - "9300:80"
    restart: "unless-stopped"

volumes:
  patch_hub_db_volume:
    external: true
  patch_hub_resource_volume:
    external: true

networks:
  patch_hub_network:
    external: true