version: "3.8"

services:
  mongodb:
    image: "mongo:latest"
    container_name: "patch_hub_mongodb"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "hGt7uB3pZrDf9iJk1qWe4rTy6uIoP2aS"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"

  nats:
    image: "nats:latest"
    container_name: "patch_hub_nats"
    restart: "always"
    ports:
      - "4222:4222"

volumes:
  mongodb_data:
